# Generated by Django 4.2.2 on 2024-09-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_alter_habit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='user',
            field=models.CharField(verbose_name='Пользователь'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
