# Generated by Django 4.2.2 on 2024-09-24 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_habit_user_habit_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='owner',
            new_name='user',
        ),
    ]
