# Generated by Django 4.2.2 on 2024-09-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_owner_habit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='frequency_in_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество раз'),
        ),
    ]
