# Generated by Django 4.2.2 on 2024-09-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_habit_frequency_in_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='frequency_in_days',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Количество раз'),
        ),
    ]
